version: '3.8'

services:
  lux-media-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "8081:8081"
    volumes:
      - /home/seabass/seastorage-V/logs/media-server-logs:/usr/src/app/logs
    command: ["pm2-runtime", "ecosystem.config.js"]