services:
  db:
    image: "postgres:latest"
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "fsync=off", "-c", "log_statement=all"]

  api:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile.api
    container_name: api
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./server:/app/lux/server
      - ./media:/app/media
    ports:
      - "${API_PORT}:${API_PORT}"

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT_OUT}:${REDIS_PORT_IN}"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  celery-worker:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile.api
    volumes:
      - ./server:/code/lux
    command: ["celery", "-A", "lux", "worker", "-l", "info"]
    depends_on:
      - redis
      - api

  celery-beat:
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile.api
    volumes:
      - ./server:/code/lux
    command: ["celery", "-A", "lux", "beat", "-l", "info"]
    depends_on:
      - redis
      - api

  server:
    container_name: nginx_proxy
    image: nginx
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - ./nginx/local/default.conf:/etc/nginx/conf.d/default.conf
    restart: "no"
    depends_on:
      - db
      - api

volumes:
  postgres_data:
    driver: local
