# Generated by Django 6.0.5 on 2026-05-10 22:20

import django.db.models.deletion
import users.models.tokens
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64, unique=True)),
                ('role', models.IntegerField(choices=[(0, 'Admin'), (1, 'Pervert'), (2, 'Adult'), (3, 'Child')], default=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('is_child_profile', models.BooleanField(default=False)),
                ('content_level_access', models.IntegerField(choices=[(0, 'Everyone'), (1, 'Teens'), (2, 'Adults'), (3, 'Perverts')], default=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InviteToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(default=users.models.tokens._generate_token, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('role', models.IntegerField(choices=[(0, 'Admin'), (1, 'Pervert'), (2, 'Adult'), (3, 'Child')])),
                ('use_count', models.IntegerField(default=0)),
                ('max_uses', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(default=users.models.tokens._generate_token, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('role', models.IntegerField(choices=[(0, 'Admin'), (1, 'Pervert'), (2, 'Adult'), (3, 'Child')])),
                ('used', models.BooleanField(default=False)),
                ('invite_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.invitetoken')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
