"""
Django settings for lux project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
import logging
import json

from lux.utils.settings.timezone import get_system_timezone
from lux.utils.settings.celery import get_celery_settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "FALSE") == "TRUE"

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "api"]
__env_allowed_host = os.getenv("ALLOWED_HOSTS")
if __env_allowed_host:
    ALLOWED_HOSTS += __env_allowed_host.split(",")

# Application definition
INSTALLED_APPS = [
    # Even though we bypass all of Django's auth system, we still need these
    # apps because DRF requires them. Even if we skip all of the stuff.
    "django.contrib.auth",
    "django.contrib.contenttypes",

    # My Stuff
    "rest_framework",
    "corsheaders",
    "lux",
    "users",
    "metadata",
    "manga",
    "video",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


CORS_ALLOW_CREDENTIALS = True

CORS_ORIGIN_WHITELIST = (
    "http://127.0.0.1",
    "http://api",
    "http://server",
    "http://localhost",
    "http://localhost:3000",
)

CORS_ALLOWED_ORIGINS = tuple(list(CORS_ORIGIN_WHITELIST) +
                            [f"http://{host}" for host in ALLOWED_HOSTS if f"http://{host}" not in CORS_ORIGIN_WHITELIST])  # noqa # pylint: disable=line-too-long

CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1",
    "http://api",
    "http://server",
    "http://localhost",
]
CSRF_TRUSTED_ORIGINS = CSRF_TRUSTED_ORIGINS \
    + [f"http://{host}" for host in ALLOWED_HOSTS if f"http://{host}" not in CSRF_TRUSTED_ORIGINS]  # noqa # pylint: disable=line-too-long

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "role",
]

ROOT_URLCONF = "lux.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
            ],
        },
    },
]

WSGI_APPLICATION = "lux.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE":  "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT", "5432"),
    },
}

# We handle the auth. There are no passwords.
AUTH_PASSWORD_VALIDATORS = []
AUTHENTICATION_BACKENDS = []

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/
LANGUAGE_CODE = "en-us"
USE_I18N = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# We aren't using these settings. But we HAVE to use it to get DRF to work.
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny"
    ],
}


class JSONFormatter(logging.Formatter):
    ''' this is a class to turn the defaults in django logging into a json format'''

    def format(self, record):
        return json.dumps({
            'timestamp': self.formatTime(record),
            'level': record.levelname,
            'message': record.getMessage(),
            'path_name': record.pathname,
            'line_number': record.lineno,
            'function_name': record.funcName,
            "file_name": record.filename
        })


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "()": "lux.settings.JSONFormatter"
        }
    },
    "handlers": {
        "file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "debug.log"),
            "formatter": "json"
        },
    },
    "loggers": {
        "": {
            "handlers": [
                "file"
            ],
            "level": "DEBUG",
            "propagate": True,
        },
        # Silence debug messages.
        'faker': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

[
    CELERY_BROKER_URL,
    CELERY_RESULT_BACKEND,
    CELERY_ACCEPT_CONTENT,
    CELERY_TASK_SERIALIZER,
    CELERY_RESULT_SERIALIZER,
    CELERY_BEAT_SCHEDULE,
    CELERY_TIMEZONE,
] = get_celery_settings()

TIME_ZONE = get_system_timezone()
USE_TZ = True
