"""
Django settings for lux project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
import logging
import json
from celery.schedules import crontab, schedule
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "FALSE") == "TRUE"

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "api"]
__env_allowed_host = os.getenv("ALLOWED_HOSTS")
if __env_allowed_host:
    ALLOWED_HOSTS += __env_allowed_host.split(",")

# Application definition
INSTALLED_APPS = [
    # Even though we bypass all of Django's auth system, we still need these
    # apps because DRF requires them. Even if we skip all of the stuff.
    "django.contrib.auth",
    "django.contrib.contenttypes",

    "rest_framework",
    "corsheaders",
    "lux",
    "users",
    "metadata",
    "manga",
    "video",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


CORS_ALLOW_CREDENTIALS = True

CORS_ORIGIN_WHITELIST = (
    "http://127.0.0.1",
    "http://api",
    "http://server",
    "http://localhost",
    "http://localhost:3000",
)

CORS_ALLOWED_ORIGINS = tuple(list(CORS_ORIGIN_WHITELIST) +
                            [f"http://{host}" for host in ALLOWED_HOSTS if f"http://{host}" not in CORS_ORIGIN_WHITELIST])  # noqa # pylint: disable=line-too-long

CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1",
    "http://api",
    "http://server",
    "http://localhost",
]
CSRF_TRUSTED_ORIGINS = CSRF_TRUSTED_ORIGINS \
    + [f"http://{host}" for host in ALLOWED_HOSTS if f"http://{host}" not in CSRF_TRUSTED_ORIGINS]  # noqa # pylint: disable=line-too-long

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "role",
]

ROOT_URLCONF = "lux.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
            ],
        },
    },
]

WSGI_APPLICATION = "lux.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE":  "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT", "5432"),
    },
}

# We handle the auth. There are no passwords.
AUTH_PASSWORD_VALIDATORS = []
AUTHENTICATION_BACKENDS = []

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/
LANGUAGE_CODE = "en-us"
USE_I18N = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        # We aren't using this. But we HAVE to use it to get DRF to work.
        "rest_framework.permissions.AllowAny"
    ],
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE":
        "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(days=30),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=30),
    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER":
        "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER":
        "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
}


class JSONFormatter(logging.Formatter):
    ''' this is a class to turn the defaults in django logging into a json format'''

    def format(self, record):
        return json.dumps({
            'timestamp': self.formatTime(record),
            'level': record.levelname,
            'message': record.getMessage(),
            'path_name': record.pathname,
            'line_number': record.lineno,
            'function_name': record.funcName,
            "file_name": record.filename
        })


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "()": "lux.settings.JSONFormatter"
        }
    },
    "handlers": {
        "file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "debug.log"),
            "formatter": "json"
        },
    },
    "loggers": {
        "": {
            "handlers": [
                "file"
            ],
            "level": "DEBUG",
            "propagate": True,
        },
    },
}

# Redis settings
# NOTE: celery wants the internal redis IP
__redis_host = os.getenv("REDIS_HOST", "redis")
__redis_port = os.getenv("REDIS_PORT_IN", "6479")

# Set transport and password based on local or server deployment
__redis_ssl = os.getenv("REDIS_SSL", None)

__redis_transport = "redis"  # pylint: disable=invalid-name
__redis_params = ""  # pylint: disable=invalid-name

if __redis_ssl is not None and __redis_ssl.lower() == "true":
    __redis_transport = "rediss"  # pylint: disable=invalid-name
    __redis_params = "?ssl_cert_reqs=required"  # pylint: disable=invalid-name

__redis_password = os.getenv("REDIS_PASSWORD", None)
if __redis_password is not None:
    CELERY_BROKER_URL = f"{__redis_transport}://default:{__redis_password}@{__redis_host}:{__redis_port}{__redis_params}"  # noqa # pylint: disable=line-too-long
else:
    CELERY_BROKER_URL = f"{
        __redis_transport}: // {__redis_host}: {__redis_port}{__redis_params}"

CELERY_RESULT_BACKEND = CELERY_BROKER_URL
CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

# Read in the schedule from a file if it exists
# NOTE: THe file stores the hour, minute, etc as strings
__celery_beat_schedule_filepath = os.getenv("CELERY_BEAT_SCHEDULE_FILEPATH")
CELERY_BEAT_SCHEDULE = {}
with open("text.txt", "w") as fp:
    fp.write("imtryin ")
    fp.write(str(__celery_beat_schedule_filepath) + " ")
    fp.write(str(os.getenv("CELERY_BEAT_SCHEDULE_FILEPATH")))
if __celery_beat_schedule_filepath and \
        os.path.exists(__celery_beat_schedule_filepath):

    with open("text2.txt", "w") as fp:
        fp.write("__celery_beat_schedule_filepath")
    schedule_data = {}
    with open(__celery_beat_schedule_filepath, "r", encoding="utf-8") as fp_in:
        schedule_data = json.load(fp_in)
        for key, value in schedule_data.items():
            value["schedule"] = crontab(**value["schedule"])
            CELERY_BEAT_SCHEDULE[key] = value

TIME_ZONE = 'America/New_York'
USE_TZ = True
CELERY_TIMEZONE = 'America/New_York'
