#!/bin/bash
# Check if a container is up and running.
# Usage:
#   ./scripts/is_container_up <container_name> [-h]
PATH=$PATH:"$(pwd)/scripts/lib"

# Function to display help
function display_help() {
    echo "Usage: $0 container_name"
    echo
    echo "Options:"
    echo "  -h                Display this help message."
}

# Parse args
if [ "$#" -eq 0 ]; then
    display_help
    exit 1
fi

is_help_requested=false
container_name=$1
shift

while [[ "$#" -gt 0 ]]; do
    case $1 in
        -h|--help)
            is_help_requested=true
            ;;
        *)
            echo "Unknown option: $1"
            display_help
            exit 1
            ;;
    esac
    shift
done

# Display help if requested
if [ "$is_help_requested" = true ]; then
    display_help
    exit 0
fi


echo "Checking if container $container_name is up and running..."
if [ $(docker ps | grep $container_name | wc -l) -eq 0 ]; then
    exit 1
else
    exit 0
fi