# Generated by Django 5.2.8 on 2025-11-16 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metadata', '0002_delete_metadatabase'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_original', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=4096, null=True)),
                ('nsfw', models.BooleanField(default=True)),
                ('studio', models.CharField(blank=True, max_length=255, null=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('has_english_license', models.BooleanField(blank=True, null=True)),
                ('tags', models.ManyToManyField(to='metadata.tags')),
                ('visited_sources', models.ManyToManyField(to='metadata.webdatasource')),
                ('video_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='video.videotypes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
