# Generated by Django 5.2.8 on 2025-11-09 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoMetadata',
            fields=[
                ('metadatabase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='metadata.metadatabase')),
                ('studio', models.CharField(blank=True, max_length=255, null=True)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('has_english_license', models.BooleanField(blank=True, null=True)),
                ('visited_sources', models.ManyToManyField(to='metadata.webdatasource')),
                ('video_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='video.videotypes')),
            ],
            options={
                'abstract': False,
            },
            bases=('metadata.metadatabase',),
        ),
    ]
