# Generated by Django 5.2.8 on 2025-11-16 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetadataBase',
        ),
    ]
